apiVersion: v2
name: grafana
description: my helm chart for grafana monitoring retrieval app

type: application

version: 0.1.0
appVersion: "1.0.0"

maintainers:
- email: duong05102002@gmail.com
  name: duongnguyen
